server:
  error:
    whitelabel:
      enabled: false   # tắt trang lỗi mặc định; mọi lỗi sẽ đi vào /error của bạn

spring:
  jpa:
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true